---
metadata:
  name: MakeCode AP CSP
  short_name: MakeCode Computer Science Principles
  description: Microsoft MakeCode Advanced Placement Computer Science Principles Curriculum
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "https://microsoft.github.io/makecode-csp/favicon.ico"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "https://microsoft.github.io/makecode-csp/assets/brand.svg"
  logoLink: "https://microsoft.github.io/makecode-csp/"
  githubRul: "https://github.com/ganicke/makecode-apcsp"
  helpUrl: ""
  links:
    - text: Teacher's Guide
      link: "/"
      external: false
    - text: PL Trainer Materials
      link: https://www.gatsbyjs.org
      external: true
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/overview"
      title: ":world_map: Overview"
    - order: 2
      path: "/unit-1"
      title: ":blue_book: Unit 1 - Intro to AP CSP"
    - order: 3
      path: "/unit-2"
      title: ":blue_book: Unit 2 - CSN"
    - order: 4
      path: "/unit-3"
      title: ":blue_book: Unit 3 - AAP part 1"
    - order: 5
      path: "/unit-4"
      title: ":blue_book: Unit 4 - IOC"
  links:
    - text: BooGi
      link: https://github.com/filipowm/boogi
    - text: React
      link: https://reactjs.org
  ignoreIndex: false
  poweredBy:
    trademark: "/assets/gatsby.png"
    name: GatsbyJS
    link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  github: https://github.com/ganicke/makecode-apcsp
  linkedin:
  twitter:

features:
  darkMode:
    enabled: true  
    default: false
  editOnRepo:
    location: https://github.com/ganicke/makecode-apcsp 
    type: github
    editable: false
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: false
    title: BooGi Docs
    showIcon: false
    copyright: "2020, Mateusz Filipowicz"
    webMaster: "Mateusz Filipowicz"
    managingEditor: "Mateusz Filipowicz"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
